#!/bin/bash
# Bootstrap librarian-puppet for root user on an Ubuntu 12.04 machine.
#
# The system is assumed to have already been configured with boostrap-linux.
#
# - Install required packages
# - Install rbenv and ruby-build
# - Set up environment
# - Install Ruby and Gems

# Install 1.8.7-p370 by default, unless RUBY_VERS environment variable is set:
default_ruby='1.8.7-p370'
RUBY_VERS=${RUBY_VERS:-$default_ruby}

if [ `id -u` -ne 0 ] ; then
  echo "Re-run this script as root - this script modifies key system files."
  exit 1
fi

/usr/bin/apt-get install build-essential libssl-dev zlib1g-dev

roothome=~root
cd $roothome
/usr/bin/git clone git://github.com/sstephenson/rbenv.git .rbenv
echo 'export PATH="$roothome/.rbenv/bin:$PATH"' >> .bash_profile
echo 'eval "$(rbenv init -)"' >> .bash_profile
/usr/bin/git clone git://github.com/sstephenson/ruby-build.git .rbenv/plugins/ruby-build

source .bash_profile

rbenv install $RUBY_VERS
rbenv shell $RUBY_VERS
gem install librarian-puppet --no-ri --no-rdoc
