#!/bin/bash
# Bootstrap puppetmaster and librarian-puppet for root user on an Ubuntu 12.04
# machine.
#
# The system is assumed to have already been configured with bootstrap-linux.
#
# - Install required packages
# - Create "git" user
# - Install rbenv and ruby-build
# - Set up environment
# - Install Ruby and Gems into Rbenv
# - Create pushable Git repos for /etc/puppet and /etc/hiera
# - Install Puppetmaster
# - Drop in /etc/puppet directory from GitHub

set -e

function usage() {
    echo "$0 [ -a <ssh authorized_keys file> ] [ -g ]"
    echo "$0 -h"
    echo
    echo "   -a    Specify authorized keys for git user"
    echo "   -g    Generate a GPG key (requires substantial entropy)"
    echo "   -h    Help (this message)"
    exit 1
}

gen_gpgkey=0
while getopts "a:gh" flag
do
    case $flag in
	a) auth_keys=$OPTARG ;;
	g) gen_gpgkey=1 ;;
	h) usage ;;
	*) usage ;;
    esac
done

# Basic test to make sure system has had bootstrap-linux run on it:
if [ ! -x /usr/bin/puppet ] ; then
    echo '/usr/bin/puppet not found; did you run bootstrap-linux?'
    echo
    usage
fi

cwd=$PWD

# Install 1.8.7-p370 by default, unless ruby_vers environment variable is set:
default_ruby='1.9.3-p484'
ruby_vers=${ruby_vers:-$default_ruby}

if [ `id -u` -ne 0 ] ; then
  echo "Re-run this script as root - this script modifies key system files."
  exit 1
fi

/usr/bin/apt-get update
/usr/bin/apt-get -y install build-essential git gnupg libssl-dev zlib1g-dev

#
# Set up bare Puppet and Hiera - pushing to these repos deploys to
# /etc/hiera, /etc/heira-gpg and /etc/puppet via a post-receive hook.
#

# Create local "git" user:
/usr/sbin/useradd -c "Git User" -U -m -s /bin/bash git

# If supplied, add SSH authorized_keys for "git" user:
if [ ! -z "$auth_keys" ] ; then
    /bin/mkdir -m 0700 ~git/.ssh
    /bin/cp $auth_keys ~git/.ssh/authorized_keys
    /bin/chown git:git ~git/.ssh ~git/.ssh/authorized_keys
    /bin/chmod 0600 ~git/.ssh/authorized_keys
fi

# Install librarian-puppet for user "git":
cd ~git
su git -c "/usr/bin/git clone git://github.com/sstephenson/rbenv.git .rbenv"
echo 'export PATH="~git/.rbenv/bin:$PATH"' >> .bash_profile
echo 'eval "$(rbenv init -)"' >> .bash_profile
chown git:git .bash_profile

su git -c "/usr/bin/git clone git://github.com/sstephenson/ruby-build.git .rbenv/plugins/ruby-build"

su -l git -c "rbenv install $ruby_vers"
su -l git -c "rbenv shell $ruby_vers && gem install librarian-puppet --no-ri --no-rdoc && gem install puppet --no-ri --no-rdoc"
su -l git -c "rbenv shell $ruby_vers && gem install r10k --no-ri --no-rdoc"

# Create pushable repos under /srv/git for Hiera and Puppet
/bin/mkdir /srv/git
/bin/chown git:git /srv/git

cd /tmp # Need to be in a directory that user "git" can access
su git -c "/usr/bin/git clone --bare git://github.com/anl/etc-puppet.git \
    /srv/git/puppet.git"

cat > /srv/git/puppet.git/hooks/post-receive <<EOF
#!/bin/bash
export PATH="~git/.rbenv/bin:$PATH"
GIT_WORK_TREE=/etc/puppet /usr/bin/git checkout -f
eval "\$(rbenv init -)"
cd /etc/puppet
rbenv shell $ruby_vers && librarian-puppet update
EOF

/bin/chown git:git /srv/git/puppet.git/hooks/post-receive
/bin/chmod 755 /srv/git/puppet.git/hooks/post-receive

/usr/bin/puppet module install cprice404-inifile -i ~/.puppet/modules
/usr/bin/git clone https://github.com/anl/anl-puppetmaster.git ~/.puppet/modules/puppetmaster
/usr/bin/puppet apply --modulepath=~/.puppet/modules -e "class { puppetmaster: hiera_gpg => true }"

for repo in hiera hiera-gpg; do
    su git -c "/usr/bin/git init --bare /srv/git/${repo}.git"

    cat > /srv/git/${repo}.git/hooks/post-receive <<EOF
#!/bin/sh
GIT_WORK_TREE=/etc/${repo} /usr/bin/git checkout -f
EOF

    /bin/chown git:git /srv/git/${repo}.git/hooks/post-receive
    /bin/chmod 755 /srv/git/${repo}.git/hooks/post-receive

    if [ -d /etc/${repo} ] ; then
	mv /etc/${repo} /etc/${repo}.orig
    fi

    /bin/mkdir -p /etc/${repo}
    /bin/chown git:git /etc/${repo}
    /bin/chmod 755 /etc/${repo}

done

if [ -d /etc/puppet ] ; then
    mv /etc/puppet /etc/puppet.orig
fi

/bin/mkdir /etc/puppet
/bin/chown git:git /etc/puppet
/bin/chmod 755 /etc/puppet

su git -c "/usr/bin/git clone git://github.com/anl/etc-puppet.git /etc/puppet"
su -l git -c "cd /etc/puppet; rbenv local $ruby_vers"
su -l git -c "cd /etc/puppet; librarian-puppet update"

if [[ $gen_gpgkey == 1 ]] ; then
    # Create a gpg key for "puppet" account:
    sudo -u puppet -H gpg --batch --gen-key <<EOF
Key-Type: RSA
Subkey-Type: RSA
Key-Length: 2048
Name-Real: Puppet
Name-Comment: hiera-gpg
Name-Email: puppet@$(hostname --fqdn)
Expire-Date: 0
Passphrase: ''
%commit
EOF
    echo "hiera-gpg public key:"
    sudo -u puppet -H gpg --export -a puppet@$(hostname)
fi

# And back to where we started:
cd $cwd
